spring.application.name=crudDemo
spring.datasource.url=jdbc:mysql://localhost:3306/post_db
spring.datasource.username=root
spring.datasource.password=grv@1998#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
